version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: zebstrika
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: