import { type Metadata } from "next";
import { Suspense } from "react";
import ListProductsByCategory from "./list-products-by-category";
import { IncrementSelector } from "./increment-selector";
import CartSummary from "./cart-summary";
import { getCategories } from "~/services";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
};

export default async function Home() {
  const categoriesData = await getCategories();

  return (
    <main className="flex min-h-screen flex-col items-start justify-start py-2">
      <div className="container flex flex-col items-start justify-start">
        <Suspense fallback={<p>Loading...</p>}>
          <ListProductsByCategory data={categoriesData} />
        </Suspense>
        <div className="fixed bottom-10 flex w-full flex-row justify-start md:justify-center">
          <IncrementSelector />
        </div>
        <div className="fixed bottom-8 right-8">
          <CartSummary />
        </div>
      </div>
    </main>
  );
}
